'use client'

import { useEffect, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { Clock, CheckCircle, XCircle, Loader2, Trash2, Info } from 'lucide-react'
import { apiClient } from '@/lib/api-client'
import { useToast } from '@/hooks/use-toast'

interface QueueItem {
  id: string
  prompt: string
  status: 'pending' | 'processing' | 'completed' | 'error'
  progress: number
  error?: string
  timestamp: Date
}

const tooltips = {
  queue: "Shows all active and recent image generations. Completed items are automatically removed after 30 seconds.",
  delete: "Remove this item from the queue. Cannot delete items that are currently processing.",
  status: {
    pending: "Waiting in queue to be processed",
    processing: "Currently being generated by ComfyUI",
    completed: "Generation completed successfully",
    error: "Generation failed. Check error message for details"
  }
}

export function GenerationQueue() {
  const [queue, setQueue] = useState<QueueItem[]>([])
  const { toast } = useToast()

  useEffect(() => {
    // Listen for generation events
    apiClient.onGenerationStart((data) => {
      setQueue(prev => [
        ...prev,
        {
          id: data.id,
          prompt: data.prompt || 'Generating...',
          status: 'pending',
          progress: 0,
          timestamp: new Date()
        }
      ])
    })

    apiClient.onGenerationProgress((data) => {
      setQueue(prev => prev.map(item => 
        item.id === data.id 
          ? { ...item, status: 'processing' as const, progress: data.progress }
          : item
      ))
    })

    apiClient.onGenerationComplete((data) => {
      setQueue(prev => prev.map(item => 
        item.id === data.id 
          ? { ...item, status: 'completed' as const, progress: 100 }
          : item
      ))
      // Remove completed items after 30 seconds
      setTimeout(() => {
        setQueue(prev => prev.filter(item => item.id !== data.id))
      }, 30000)
    })

    apiClient.onGenerationError((data) => {
      setQueue(prev => prev.map(item => 
        item.id === data.id 
          ? { ...item, status: 'error' as const, error: data.error }
          : item
      ))
      // Remove error items after 60 seconds
      setTimeout(() => {
        setQueue(prev => prev.filter(item => item.id !== data.id))
      }, 60000)
    })

    return () => {
      // Clean up listeners if needed
    }
  }, [])

  const getStatusIcon = (status: QueueItem['status']) => {
    switch (status) {
      case 'pending':
        return <Clock className="h-4 w-4" />
      case 'processing':
        return <Loader2 className="h-4 w-4 animate-spin" />
      case 'completed':
        return <CheckCircle className="h-4 w-4" />
      case 'error':
        return <XCircle className="h-4 w-4" />
    }
  }

  const getStatusColor = (status: QueueItem['status']) => {
    switch (status) {
      case 'pending':
        return 'secondary'
      case 'processing':
        return 'default'
      case 'completed':
        return 'success'
      case 'error':
        return 'destructive'
    }
  }

  const handleDelete = async (id: string) => {
    const item = queue.find(q => q.id === id)
    if (!item) return

    if (item.status === 'processing') {
      toast({
        title: "Cannot delete",
        description: "Cannot delete items that are currently being processed.",
        variant: "destructive"
      })
      return
    }

    try {
      // Remove from local state immediately for responsiveness
      setQueue(prev => prev.filter(q => q.id !== id))
      // If there's an API endpoint to cancel, call it here
      // await apiClient.cancelGeneration(id)
      toast({
        title: "Item removed",
        description: "The item has been removed from the queue."
      })
    } catch (error) {
      // Re-add if deletion failed
      setQueue(prev => [...prev, item])
      toast({
        title: "Delete failed",
        description: "Failed to remove the item from the queue.",
        variant: "destructive"
      })
    }
  }

  if (queue.length === 0) {
    return null
  }

  return (
    <TooltipProvider>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CardTitle className="text-base">Generation Queue</CardTitle>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Info className="h-4 w-4 text-muted-foreground cursor-help" />
                </TooltipTrigger>
                <TooltipContent className="max-w-xs">
                  <p>{tooltips.queue}</p>
                </TooltipContent>
              </Tooltip>
            </div>
          </div>
        </CardHeader>
      <CardContent className="space-y-3">
        {queue.map((item) => (
          <div key={item.id} className="space-y-2 p-3 border rounded-lg">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                {getStatusIcon(item.status)}
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Badge variant={getStatusColor(item.status)}>
                      {item.status}
                    </Badge>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>{tooltips.status[item.status]}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-xs text-muted-foreground">
                  {item.timestamp.toLocaleTimeString()}
                </span>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={() => handleDelete(item.id)}
                      disabled={item.status === 'processing'}
                      className="h-6 w-6"
                    >
                      <Trash2 className="h-3 w-3" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>
                    <p>{tooltips.delete}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
            
            <p className="text-sm text-muted-foreground truncate">
              {item.prompt}
            </p>
            
            {item.status === 'processing' && (
              <div className="space-y-1">
                <Progress value={item.progress} className="h-2" />
                <p className="text-xs text-right text-muted-foreground">
                  {item.progress}%
                </p>
              </div>
            )}
            
            {item.error && (
              <p className="text-xs text-destructive">
                Error: {item.error}
              </p>
            )}
          </div>
        ))}
      </CardContent>
    </Card>
    </TooltipProvider>
  )
}