#!/bin/bash

echo "🚀 LM Studio Setup Guide"
echo "======================"
echo ""
echo "LM Studio is a desktop application that must be installed manually."
echo ""
echo "📥 Installation Steps:"
echo ""
echo "1. Download LM Studio from: https://lmstudio.ai/"
echo "   - Available for Windows, macOS, and Linux"
echo "   - Choose the version for your operating system"
echo ""
echo "2. Install the application:"
echo "   - Windows: Run the .exe installer"
echo "   - macOS: Drag to Applications folder"
echo "   - Linux: Extract and run the AppImage"
echo ""
echo "3. Launch LM Studio and download models:"
echo "   - Click 'Browse' in the sidebar"
echo "   - Search for models (e.g., 'llama', 'mistral', 'deepseek')"
echo "   - Download models with GGUF format"
echo "   - Recommended models:"
echo "     • TheBloke/Llama-2-7B-Chat-GGUF"
echo "     • TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
echo "     • TheBloke/deepseek-coder-6.7b-instruct-GGUF"
echo ""
echo "4. Load a model:"
echo "   - Go to the 'Local Server' tab"
echo "   - Select a downloaded model"
echo "   - Click 'Start Server'"
echo "   - Default port is 1234"
echo ""
echo "5. Verify the connection:"
echo "   - The server should show as running in LM Studio"
echo "   - You can test with: curl http://localhost:1234/v1/models"
echo ""
echo "📝 Configuration:"
echo ""
echo "Add to your .env file:"
echo "LMSTUDIO_HOST=ws://localhost"
echo "LMSTUDIO_PORT=1234"
echo "LMSTUDIO_DEFAULT_MODEL=<your-model-name>"
echo ""
echo "🔧 Tips:"
echo "- LM Studio must be running for the API to connect"
echo "- Models are stored in ~/LMStudio/models (or AppData on Windows)"
echo "- You can run multiple models but only one at a time"
echo "- GPU acceleration is automatic if available"
echo ""
echo "📚 More Information:"
echo "- LM Studio Docs: https://lmstudio.ai/docs"
echo "- Model Library: https://huggingface.co/models?other=gguf"
echo ""