#!/bin/bash

echo "🚀 LocalAI Setup Guide"
echo "===================="
echo ""
echo "LocalAI is a drop-in replacement for OpenAI API that runs completely offline."
echo "It supports multiple model backends and multi-modal capabilities."
echo ""
echo "📥 Installation Methods:"
echo ""
echo "1. Docker (Recommended):"
echo "   cd docker/localai"
echo "   docker-compose up -d"
echo ""
echo "2. Binary Installation:"
echo "   # Download latest release"
echo "   curl -Lo local-ai https://github.com/mudler/LocalAI/releases/latest/download/local-ai-$(uname -s)-$(uname -m)"
echo "   chmod +x local-ai"
echo "   sudo mv local-ai /usr/local/bin/"
echo ""
echo "3. From Source:"
echo "   git clone https://github.com/mudler/LocalAI"
echo "   cd LocalAI"
echo "   make build"
echo ""
echo "📦 Downloading Models:"
echo ""
echo "1. Using Model Gallery (automatic):"
echo "   # Models are downloaded automatically when first used"
echo "   # Available models: https://github.com/go-skynet/model-gallery"
echo ""
echo "2. Manual Download:"
echo "   cd docker/localai/models"
echo "   # Download GGUF models from Hugging Face"
echo "   wget https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf"
echo ""
echo "3. Using LocalAI CLI:"
echo "   local-ai models list"
echo "   local-ai models install llama-3.1-8b-instruct"
echo ""
echo "🔧 Configuration:"
echo ""
echo "Add to your .env file:"
echo "LOCALAI_HOST=http://localhost"
echo "LOCALAI_PORT=8080"
echo "LOCALAI_API_KEY=sk-localai-dummy"
echo "LOCALAI_DEFAULT_MODEL=llama3"
echo ""
echo "📝 Multi-Modal Features:"
echo ""
echo "- Text Generation: OpenAI-compatible chat/completions"
echo "- Image Generation: Stable Diffusion support"
echo "- Speech Synthesis: TTS with multiple voices"
echo "- Speech Recognition: Whisper integration"
echo "- Embeddings: Text embedding generation"
echo ""
echo "🎯 Quick Test:"
echo ""
echo "# Health check"
echo "curl http://localhost:8080/readyz"
echo ""
echo "# List models"
echo "curl http://localhost:8080/v1/models"
echo ""
echo "# Test generation"
echo 'curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '"'"'{"model": "llama3", "messages": [{"role": "user", "content": "Hello!"}]}'"'"
echo ""
echo "📚 More Information:"
echo "- LocalAI Docs: https://localai.io/"
echo "- Model Gallery: https://github.com/go-skynet/model-gallery"
echo "- Discord: https://discord.gg/localai"
echo ""